### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Pantonia4** [CDAGaming/CraftPresence-Wow-Edition#2] opened 2024-04-14 16:21 UTC
Followed the instructions, and even redid everything twice, but Discord is still only showing "playing World of Warcraft" and nothing else. There is no Error and according to the Debug Log it manages to find out the current location etc. 

![Screenshot 2024-04-14 180717](https://github.com/CDAGaming/CraftPresence-Wow-Edition/assets/153833661/381eb709-63f9-45d6-bf8d-f3f87f39374e)
![Screenshot 2024-04-14 180726](https://github.com/CDAGaming/CraftPresence-Wow-Edition/assets/153833661/6295fcb9-25df-4f0a-9f68-962c0fc395e4)

The script itself is also running without an Error
![image](https://github.com/CDAGaming/CraftPresence-Wow-Edition/assets/153833661/21883254-2d5e-466b-af90-dffe4c7892c5)

Logs all show the same:
04/13/2024 09:36:06 PM [INFO] ========== DiscordRichPresence Service - v1.7.7 ==========
04/13/2024 09:36:06 PM [INFO] System Info: "3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]"
04/13/2024 09:36:06 PM [INFO] Started DiscordRichPresence Service for "World of Warcraft"
04/13/2024 09:36:06 PM [INFO] Note: Please keep this script open while logging and sending Rich Presence updates.
04/13/2024 09:36:06 PM [INFO] ==========================================================

So I guess the issue is that the AddOn is unable to communicate with the script.

**Comment by CDAGaming** [comment] 2024-04-14 18:54
You'd be correct in your guess 👍 

Normally, in cases like this, the issue relates to your Game's Settings (Specifically settings like HDR, Gamma, Brightness, Contrast, and other settings that can effect how the game's colors look)

For those settings, they need to be at their default values for the AddOn to properly communicate with the script.
Please verify these settings on your end, and if possible, please attach screenshots of your game settings if the issue persists.

**Comment by Pantonia4** [comment] 2024-04-15 18:24
I tried the default settings, no other AddOns and disabled HDR. Also tried in Classic and WotLK. It doesn't work anywhere. And as I said the AddOn manages to find my location etc. according to Debug, it just not sending the info to the DiscordRichPresence script. But its not the end of the world so no need to look deeper into it.

**Comment by CDAGaming** [comment] 2024-04-15 20:11
"it just not sending the info to the DiscordRichPresence script"

As mentioned, the only way this can happen is that the python script is unable to interpret the RPCEvent the Addon is creating, which is often caused by a color discrepancy.

I'll close this as-is, if you truly don't wish for me to look deeper into this, though I will also mention that software like ReShade will also cause issues with this addon.

**Closed as completed by CDAGaming** 2024-04-15 20:11 UTC
Labels: bug
